# Generated by Django 4.1.5 on 2023-02-04 14:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0009_alter_order_order_datetime_alter_ticket_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_datetime',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 4, 17, 22, 30, 276826)),
        ),
        migrations.AlterField(
            model_name='product',
            name='info_product',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
