# Generated by Django 4.1.5 on 2023-02-04 14:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0011_remove_order_user_remove_ticket_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_datetime',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 4, 17, 59, 37, 746206)),
        ),
    ]
